# Generated by Django 5.1.15 on 2026-07-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="floor_number",
            field=models.IntegerField(
                blank=True,
                help_text="1 = 1st floor (200-series), 2 = 2nd floor (300-series).",
                null=True,
            ),
        ),
    ]
