# Generated by Django 5.1.15 on 2026-07-08 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ships", "0004_seed_mv_alaska_rooms"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("day_1", "Day 1"),
                            ("day_2", "Day 2"),
                            ("day_3", "Day 3"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("snacks", "Snacks"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to hide without deleting."
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Display order within the same day/meal."
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_menu_items",
                        to="ships.ship",
                    ),
                ),
            ],
            options={
                "ordering": ["ship", "day", "meal_type", "order", "id"],
            },
        ),
    ]
