# Generated by Django 5.1.15 on 2026-07-12 07:18

from django.db import migrations, models

#: The numbers already printed on the reports/invoices before this field
#: existed. Backfilled onto existing ships so migrating changes nothing on
#: screen; new ships start blank and inherit the settings default.
DEFAULT_PHONES = "01712-823482, 01831-694307, 01342-919795"


def seed_existing_ships(apps, schema_editor):
    Ship = apps.get_model("ships", "Ship")
    Ship.objects.filter(authority_phones="").update(authority_phones=DEFAULT_PHONES)


class Migration(migrations.Migration):

    dependencies = [
        ("ships", "0006_seed_mv_alaska_food_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="authority_phones",
            field=models.CharField(
                blank=True,
                help_text="Helpline numbers for the report/invoice header, comma-separated.",
                max_length=255,
            ),
        ),
        migrations.RunPython(seed_existing_ships, migrations.RunPython.noop),
    ]
