# Generated by Django 5.1.15 on 2026-07-17 05:29

import apps.ships.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ships", "0008_roomimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cabin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL id, e.g. premier-balcony-suite. Auto-generated from the name when left blank.",
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="One-line teaser under the name on the detail page.",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Long 'About this cabin' text on the detail page.",
                    ),
                ),
                (
                    "size_label",
                    models.CharField(
                        blank=True,
                        help_text='Shown on the card badge, e.g. "32 m²".',
                        max_length=30,
                    ),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("highlights", models.JSONField(blank=True, default=list)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide from the website without deleting.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower numbers show first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Used to show occupancy (max adults/kids) on the cabin card.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cabins",
                        to="ships.roomtype",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cabins",
                        to="ships.ship",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CabinImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=apps.ships.models.cabin_image_path),
                ),
                ("caption", models.CharField(blank=True, max_length=150)),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Shown on the cabin card. Only one per cabin.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower numbers show first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cabin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ships.cabin",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_main", "sort_order", "id"],
            },
        ),
    ]
