# Generated by Django 5.1.15 on 2026-07-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ships", "0011_galleryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="contact_notify_email",
            field=models.EmailField(
                blank=True,
                help_text="Inbox for website contact-form messages. Blank uses the system default.",
                max_length=254,
            ),
        ),
    ]
