# Generated by Django 5.1.15 on 2026-07-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ships", "0012_ship_contact_notify_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="guide_report_density",
            field=models.CharField(
                choices=[
                    ("compact", "Compact"),
                    ("normal", "Normal"),
                    ("large", "Large"),
                ],
                default="normal",
                help_text="Guide report PDF text size / rows-per-page.",
                max_length=10,
            ),
        ),
    ]
