# Generated by Django 5.1.15 on 2026-08-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ships", "0014_food_menu_evening_snacks"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="group_min_pax",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Pax count at which the dashboard suggests marking a booking as a group. A suggestion only — booking_type is always set by a human.",
            ),
        ),
        migrations.AddField(
            model_name="ship",
            name="refund_claim_window_days",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Days after a sailing ends within which staff may raise a refund normally. Later claims need an explicit override, so a closed accounting month is never reopened by accident.",
            ),
        ),
        migrations.AddField(
            model_name="ship",
            name="refund_sla_days",
            field=models.PositiveSmallIntegerField(
                default=14,
                help_text="Working days quoted to the customer for a refund payout. Drives the promise in the cancellation email and the overdue-refund alert.",
            ),
        ),
    ]
