# Generated by Django 5.1.15 on 2026-09-09 13:36

from django.db import migrations, models


def shorten_existing_promise(apps, schema_editor):
    """Bring ships still on the old 14-day promise down to 10.

    Altering the default alone would leave every existing ship quoting 14 days
    on the live site, which is the number SSLCommerz's merchant review rejects.
    Only rows still sitting on the old default are touched — a ship whose
    operator has deliberately set some other figure keeps it.
    """
    apps.get_model("ships", "Ship").objects.filter(refund_sla_days=14).update(
        refund_sla_days=10
    )


class Migration(migrations.Migration):

    dependencies = [
        ("ships", "0015_ship_group_min_pax_ship_refund_claim_window_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ship",
            name="refund_sla_days",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Working days quoted to the customer as the outside limit for a refund to reach them — end to end, not just our own leg. Drives the promise in the cancellation email and the overdue-refund alert. SSLCommerz require a published standard timeline of 7 to 10 working days, so do not raise this above 10 without checking the merchant terms.",
            ),
        ),
        migrations.RunPython(
            shorten_existing_promise, migrations.RunPython.noop, elidable=True
        ),
    ]
