# Generated by Django 5.1.15 on 2026-09-17 09:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ships", "0016_refund_sla_ten_working_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="default_adult_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Pre-fills the per-adult fare on a new package. Each sailing can still be priced differently; this is only the starting figure.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
