# Generated by Django 5.1.15 on 2026-09-17 09:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ships", "0017_ship_default_adult_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="meal_allowance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Deducted once per empty adult berth — the food that guest would have eaten over the trip. 0 charges strictly per person instead.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
