# Generated by Django 5.1.15 on 2026-09-17 09:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ships", "0018_ship_meal_allowance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ship",
            name="meal_allowance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Leave blank to charge per person. Set it to sell whole cabins, returning this much for each empty adult berth — the food that guest would have eaten over the trip.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
