# Generated by Django 5.1.15 on 2026-09-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Administrator"), ("booking", "Booking staff")],
                default="admin",
                help_text="Administrators manage everything. Booking staff work with bookings, payments and invoices, and can read the sailings and cabins they need to book against — but cannot change prices, offers, refunds or other staff.",
                max_length=20,
            ),
        ),
    ]
