# Generated by Django 5.1.15 on 2026-09-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_capabilities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("booking", "Staff (chosen permissions)"),
                ],
                default="admin",
                help_text="Administrators can do everything, including managing other accounts. Everyone else can do exactly what is ticked in their capabilities, and can never manage accounts.",
                max_length=20,
            ),
        ),
    ]
