"""Showcase cabins (Cabin/CabinImage) — public catalog API + staff CRUD.

The /cabins pages are fully staff-managed marketing content: the public API
must be price-free, active-only, slug-addressed; the staff API owns CRUD,
gallery uploads, and the single-main-image invariant.
"""

from decimal import Decimal

from django.contrib.auth import get_user_model
from django.core.files.uploadedfile import SimpleUploadedFile
from rest_framework.test import APITestCase

from apps.ships.models import Cabin, CabinImage, RoomType, Ship, cabin_image_path
from apps.testing import ThrottlelessTestMixin

User = get_user_model()

# 1x1 px valid GIF — enough for ImageField validation without Pillow gymnastics.
TINY_GIF = (
    b"GIF89a\x01\x00\x01\x00\x80\x00\x00\x00\x00\x00\xff\xff\xff!\xf9\x04"
    b"\x01\x00\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D"
    b"\x01\x00;"
)


def make_image(name="cabin.gif"):
    return SimpleUploadedFile(name, TINY_GIF, content_type="image/gif")


class CabinTestCase(ThrottlelessTestMixin, APITestCase):
    @classmethod
    def setUpTestData(cls):
        cls.ship = Ship.objects.create(name="Cabin Test Ship")
        cls.room_type, _ = RoomType.objects.get_or_create(
            name="2-Person Room",
            defaults=dict(max_adults=2, max_kids=1, base_price=Decimal("2000.00")),
        )
        cls.cabin = Cabin.objects.create(
            ship=cls.ship,
            room_type=cls.room_type,
            name="Test Panorama Cabin",
            tagline="Sweeping views.",
            description="Long description.",
            size_label="26 m²",
            features=["Panoramic windows", "Queen bed"],
            amenities=[{"label": "Size", "value": "26 m²"}],
            highlights=[{"title": "Windows", "desc": "Very big."}],
            sort_order=1,
        )
        cls.hidden = Cabin.objects.create(
            ship=cls.ship, name="Hidden Cabin", is_active=False, sort_order=2
        )
        cls.staff = User.objects.create_user(
            username="cabinstaff", password="pass12345", is_staff=True
        )

    def auth(self):
        tokens = self.client.post(
            "/api/staff/login/", {"username": "cabinstaff", "password": "pass12345"}
        ).data
        self.client.credentials(HTTP_AUTHORIZATION=f"Bearer {tokens['access']}")

    # ── model behavior ────────────────────────────────────────────────────

    def test_slug_autogenerated_and_unique(self):
        first = Cabin.objects.create(ship=self.ship, name="Royal Suite")
        second = Cabin.objects.create(ship=self.ship, name="Royal Suite")
        self.assertEqual(first.slug, "royal-suite")
        self.assertEqual(second.slug, "royal-suite-2")

    def test_upload_path_keyed_by_ship_and_slug(self):
        image = CabinImage(cabin=self.cabin)
        path = cabin_image_path(image, "photo.jpg")
        self.assertEqual(
            path, f"cabins/{self.ship.pk}/{self.cabin.slug}/photo.jpg"
        )

    def test_only_one_main_image_per_cabin(self):
        first = CabinImage.objects.create(
            cabin=self.cabin, image=make_image(), is_main=True
        )
        second = CabinImage.objects.create(
            cabin=self.cabin, image=make_image(), is_main=True
        )
        first.refresh_from_db()
        self.assertTrue(second.is_main)
        self.assertFalse(first.is_main, "previous main must be cleared")

    # ── public API ────────────────────────────────────────────────────────

    def test_public_list_active_only_and_price_free(self):
        response = self.client.get("/api/cabins/")
        self.assertEqual(response.status_code, 200)
        cabins = {c["slug"]: c for c in response.json()}
        # The seed migration's cabins are also present — assert membership,
        # not exact equality.
        self.assertIn(self.cabin.slug, cabins)
        self.assertNotIn(
            self.hidden.slug, cabins, "inactive cabins must not be listed"
        )
        payload = cabins[self.cabin.slug]
        self.assertEqual(payload["occupancy"], "2 Adults + 1 Kids")
        self.assertEqual(payload["features"], ["Panoramic windows", "Queen bed"])
        for forbidden in ("price", "base_price"):
            self.assertNotIn(forbidden, payload, "cabins API must be price-free")

    def test_public_detail_by_slug_with_gallery(self):
        main = CabinImage.objects.create(
            cabin=self.cabin, image=make_image(), is_main=True, caption="Hero"
        )
        CabinImage.objects.create(
            cabin=self.cabin, image=make_image(), caption="Bathroom", sort_order=1
        )
        response = self.client.get(f"/api/cabins/{self.cabin.slug}/")
        self.assertEqual(response.status_code, 200)
        payload = response.json()
        self.assertEqual(payload["description"], "Long description.")
        self.assertEqual(payload["amenities"], [{"label": "Size", "value": "26 m²"}])
        self.assertEqual(payload["highlights"], [{"title": "Windows", "desc": "Very big."}])
        self.assertEqual(len(payload["images"]), 2)
        self.assertEqual(
            payload["images"][0]["id"], main.pk, "main image must come first"
        )
        self.assertEqual(payload["main_image"]["id"], main.pk)

    def test_main_image_falls_back_to_first_gallery_photo(self):
        photo = CabinImage.objects.create(cabin=self.cabin, image=make_image())
        response = self.client.get("/api/cabins/")
        payload = next(
            c for c in response.json() if c["slug"] == self.cabin.slug
        )
        self.assertEqual(payload["main_image"]["id"], photo.pk)

    def test_public_detail_hidden_cabin_404s(self):
        response = self.client.get(f"/api/cabins/{self.hidden.slug}/")
        self.assertEqual(response.status_code, 404)

    # ── staff API ─────────────────────────────────────────────────────────

    def test_staff_endpoints_require_auth(self):
        self.assertEqual(self.client.get("/api/staff/cabins/").status_code, 401)
        self.assertEqual(self.client.post("/api/staff/cabin-images/").status_code, 401)

    def test_staff_create_cabin_autogenerates_slug(self):
        self.auth()
        response = self.client.post(
            "/api/staff/cabins/",
            {
                "ship": self.ship.pk,
                "room_type": self.room_type.pk,
                "name": "Honeymoon Suite",
                "features": ["Rose petals "],
                "amenities": [{"label": "Bed", "value": "King"}],
                "highlights": [],
            },
            format="json",
        )
        self.assertEqual(response.status_code, 201, response.content)
        self.assertEqual(response.data["slug"], "honeymoon-suite")
        self.assertEqual(
            response.data["features"], ["Rose petals"], "features must be trimmed"
        )

    def test_staff_rejects_malformed_content_lists(self):
        self.auth()
        base = {"ship": self.ship.pk, "name": "Broken"}
        bad_features = self.client.post(
            "/api/staff/cabins/", {**base, "features": [{"not": "a string"}]}, format="json"
        )
        self.assertEqual(bad_features.status_code, 400)
        bad_amenities = self.client.post(
            "/api/staff/cabins/", {**base, "amenities": [{"label": "x"}]}, format="json"
        )
        self.assertEqual(bad_amenities.status_code, 400)
        bad_highlights = self.client.post(
            "/api/staff/cabins/", {**base, "highlights": ["plain string"]}, format="json"
        )
        self.assertEqual(bad_highlights.status_code, 400)

    def test_staff_upload_and_set_main(self):
        self.auth()
        upload = self.client.post(
            "/api/staff/cabin-images/",
            {"cabin": self.cabin.pk, "image": make_image(), "caption": "Bed"},
            format="multipart",
        )
        self.assertEqual(upload.status_code, 201, upload.content)
        self.assertIn("image_url", upload.data)
        second = self.client.post(
            "/api/staff/cabin-images/",
            {"cabin": self.cabin.pk, "image": make_image(), "is_main": True},
            format="multipart",
        )
        self.assertEqual(second.status_code, 201)

        # Promote the first upload — the second must lose its main flag.
        promote = self.client.patch(
            f"/api/staff/cabin-images/{upload.data['id']}/",
            {"is_main": True},
            format="json",
        )
        self.assertEqual(promote.status_code, 200)
        flags = {
            img.pk: img.is_main
            for img in CabinImage.objects.filter(cabin=self.cabin)
        }
        self.assertTrue(flags[upload.data["id"]])
        self.assertFalse(flags[second.data["id"]])

    def test_staff_image_cabin_is_immutable(self):
        self.auth()
        other = Cabin.objects.create(ship=self.ship, name="Other Cabin")
        photo = CabinImage.objects.create(cabin=self.cabin, image=make_image())
        response = self.client.patch(
            f"/api/staff/cabin-images/{photo.pk}/",
            {"cabin": other.pk},
            format="json",
        )
        self.assertEqual(response.status_code, 200)
        photo.refresh_from_db()
        self.assertEqual(photo.cabin_id, self.cabin.pk, "cabin must not change")

    def test_staff_list_includes_inactive(self):
        self.auth()
        response = self.client.get("/api/staff/cabins/")
        self.assertEqual(response.status_code, 200)
        slugs = [c["slug"] for c in response.data]
        self.assertIn(self.hidden.slug, slugs)
