# Generated by Django 5.1.15 on 2026-07-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="inquiry_type",
            field=models.CharField(
                choices=[
                    ("general", "General inquiry"),
                    ("family", "Family trip"),
                    ("corporate", "Corporate / group trip"),
                    ("charter", "Full ship charter"),
                ],
                default="general",
                help_text="What kind of trip the customer is asking about.",
                max_length=20,
            ),
        ),
    ]
