# Generated by Django 5.1.15 on 2026-07-07 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ships", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KidPricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_age",
                    models.PositiveSmallIntegerField(
                        help_text="Inclusive lower bound."
                    ),
                ),
                (
                    "max_age",
                    models.PositiveSmallIntegerField(
                        help_text="Exclusive upper bound."
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("fixed", "Fixed amount"),
                            ("full_adult", "Full adult charge"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Required only for fixed-amount rules.",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["min_age"],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "booking_cutoff_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank to auto-set to 12:00 PM (noon) the day before the tour start date.",
                        null=True,
                    ),
                ),
                (
                    "adult_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Charge per adult for this package.",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "is_booking_open",
                    models.BooleanField(
                        default=True,
                        help_text="Manual override: uncheck to close booking regardless of cutoff.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packages",
                        to="ships.ship",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PackageRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_rooms",
                        to="packages.package",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="package_rooms",
                        to="ships.room",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="package",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="package_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="packageroom",
            constraint=models.UniqueConstraint(
                fields=("package", "room"), name="uniq_room_per_package"
            ),
        ),
    ]
