# Generated by Django 5.1.15 on 2026-07-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="hero_image",
            field=models.ImageField(blank=True, upload_to="packages/hero/"),
        ),
        migrations.AddField(
            model_name="package",
            name="highlights",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of short strings, e.g. ["Mangrove safari", "Sunset dinner"].',
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="marketing_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="package",
            name="marketing_title",
            field=models.CharField(
                blank=True, help_text='e.g. "Sundarbans Explorer".', max_length=100
            ),
        ),
    ]
