# Generated by Django 5.1.15 on 2026-07-10 14:01

import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0002_package_hero_image_package_highlights_and_more"),
        ("ships", "0006_seed_mv_alaska_food_menu"),
    ]

    operations = [
        # GiST equality on the plain ship FK column needs btree_gist.
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name="package",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(
                    ("status__in", ("draft", "cancelled")), _negated=True
                ),
                expressions=[
                    ("ship", "="),
                    (
                        models.Func(
                            models.F("start_date"),
                            models.F("end_date"),
                            function="daterange",
                        ),
                        "&&",
                    ),
                ],
                name="excl_ship_package_date_overlap",
            ),
        ),
    ]
