# Generated by Django 5.1.15 on 2026-07-11 10:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0003_package_excl_ship_package_date_overlap"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="balance_due_days_before_start",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Days before departure by which the remaining balance must be settled (deadline is noon that day). Partially paid bookings past the deadline are cancelled and flagged for a manual refund call.",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="min_deposit_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Minimum first payment as % of the booking total (invoice policy: confirmation requires a 50% advance). Top-ups toward an existing balance are exempt.",
                max_digits=5,
            ),
        ),
    ]
