# Generated by Django 5.1.15 on 2026-07-11 18:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def clamp_out_of_range_deposits(apps, schema_editor):
    """Repair bug-era rows (QA M5).

    min_deposit_percent had no bounds, so a package could carry 0 (one paisa
    holds a cabin forever — the C2 bug this field exists to prevent) or >100
    (partial payment silently impossible). Clamp any such row into the valid
    range before the validators start being enforced.
    """
    Package = apps.get_model("packages", "Package")
    Package.objects.filter(min_deposit_percent__lt=Decimal("1.00")).update(
        min_deposit_percent=Decimal("50.00")  # back to the documented policy
    )
    Package.objects.filter(min_deposit_percent__gt=Decimal("100.00")).update(
        min_deposit_percent=Decimal("100.00")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0004_package_balance_due_days_before_start_and_more"),
    ]

    operations = [
        migrations.RunPython(
            clamp_out_of_range_deposits, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="package",
            name="min_deposit_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Minimum first payment as % of the booking total, 1-100 (invoice policy: confirmation requires a 50% advance). Top-ups toward an existing balance are exempt.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("1.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
    ]
