# Generated by Django 5.1.15 on 2026-07-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0005_alter_package_min_deposit_percent"),
        ("ships", "0007_ship_authority_phones"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["status", "end_date"], name="package_status_end_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["start_date"], name="package_start_idx"),
        ),
    ]
