# Generated by Django 5.1.15 on 2026-07-18 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0006_package_package_status_end_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="packageroom",
            name="block_reason",
            field=models.CharField(
                blank=True,
                help_text="Internal note on why the room is held (never shown to customers).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="packageroom",
            name="blocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packageroom",
            name="blocked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="packageroom",
            name="is_blocked",
            field=models.BooleanField(
                default=False,
                help_text="Admin hold — withhold this room from sale without deleting it.",
            ),
        ),
    ]
