# Generated by Django 5.1.15 on 2026-07-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0007_packageroom_block_reason_packageroom_blocked_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="duration_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Leave blank to auto-calculate (nights + 1) from the dates.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="duration_nights",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Leave blank to auto-calculate from the dates (end − start).",
                null=True,
            ),
        ),
    ]
