# Generated by Django 5.1.15 on 2026-08-09 09:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0008_package_duration_days_package_duration_nights"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="foreigner_adult_surcharge",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Extra charge per foreign adult, on top of the adult fare.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="foreigner_kid_surcharge",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Extra charge per foreign child, on top of that child's age-tier fare. A child on a FREE age tier is still surcharged if set.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
