# Generated by Django 5.1.15 on 2026-08-09 12:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def carry_rates_to_the_policy_row(apps, schema_editor):
    """Lift any per-package surcharge onto the single global row.

    The per-package fields shipped only hours before this change, so in
    practice they are all 0.00 — but "in practice" is not a guarantee, and the
    columns are dropped immediately below. Taking the highest configured rate
    means a staff member who had already priced a sailing does not silently
    lose it, and errs toward charging rather than under-charging. Bookings
    already made are unaffected either way: each froze its own rate into
    price_snapshot when it was created.
    """
    Package = apps.get_model("packages", "Package")
    ForeignerSurcharge = apps.get_model("packages", "ForeignerSurcharge")

    highest = Package.objects.aggregate(
        adult=models.Max("foreigner_adult_surcharge"),
        kid=models.Max("foreigner_kid_surcharge"),
    )
    ForeignerSurcharge.objects.update_or_create(
        pk=1,
        defaults={
            "adult_amount": highest["adult"] or Decimal("0.00"),
            "kid_amount": highest["kid"] or Decimal("0.00"),
        },
    )


def drop_the_policy_row(apps, schema_editor):
    """Reverse: the per-package columns come back with their own defaults, so
    the policy row has nothing left to describe."""
    apps.get_model("packages", "ForeignerSurcharge").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0009_package_foreigner_adult_surcharge_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForeignerSurcharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adult_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Extra charge per foreign adult, on top of the adult fare.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "kid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Extra charge per foreign child, on top of that child's age-tier fare. A child on a FREE age tier is still surcharged if set.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Foreigner surcharge",
                "verbose_name_plural": "Foreigner surcharge",
            },
        ),
        # Must run BEFORE the columns are dropped — it reads them.
        migrations.RunPython(carry_rates_to_the_policy_row, drop_the_policy_row),
        migrations.RemoveField(
            model_name="package",
            name="foreigner_adult_surcharge",
        ),
        migrations.RemoveField(
            model_name="package",
            name="foreigner_kid_surcharge",
        ),
    ]
