# Generated by Django 5.1.15 on 2026-09-17 06:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0010_foreigner_surcharge_global"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("none", "No offer"),
                    ("percent", "Percentage off"),
                    ("fixed", "Fixed amount off, per cabin"),
                ],
                default="none",
                help_text="What kind of reduction, if any, this sailing is sold at.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Percent off, or taka off PER CABIN — a 3-cabin booking gets a fixed discount three times, once against each cabin, because that is how the cabins are priced.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="offer_ends_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the offer stops applying (Bangladesh time). Leave blank to run it until the discount is removed by hand. Bookings already priced keep the discount they were given.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="offer_label",
            field=models.CharField(
                blank=True,
                help_text='Shown on the public cards, e.g. "Eid Offer" or "Early Bird".',
                max_length=60,
            ),
        ),
    ]
