# Generated by Django 5.1.15 on 2026-09-28 20:38

import apps.promotions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("packages", "0011_package_offer"),
        ("ships", "0019_meal_allowance_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_label",
                    models.CharField(
                        blank=True,
                        help_text='Small pill above the headline, e.g. "EID OFFER" or "LIMITED SEATS".',
                        max_length=40,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The headline. Keep it short — it is set large.",
                        max_length=120,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="One supporting line, shown under the headline everywhere.",
                        max_length=200,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Longer text, shown only in the modal where there is room for it. The hero strip and the home banner never show this.",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Banner artwork for the modal and the home section. Optional — without it both fall back to a text-only layout that still looks deliberate, so a promotion is never blocked on waiting for a designer.",
                        null=True,
                        upload_to=apps.promotions.models.promotion_image_path,
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(
                        blank=True,
                        help_text='Button text, e.g. "See packages". Leave blank for no button.',
                        max_length=40,
                    ),
                ),
                (
                    "cta_url",
                    models.CharField(
                        blank=True,
                        help_text='Where the button goes — a path on this site ("/packages") or a full URL. Ignored when a package is linked below.',
                        max_length=300,
                    ),
                ),
                (
                    "show_in_modal",
                    models.BooleanField(
                        default=True,
                        help_text="Pop up on the home page shortly after the visitor arrives.",
                    ),
                ),
                (
                    "show_in_hero",
                    models.BooleanField(
                        default=True,
                        help_text="A slim strip across the hero, on every page that has one.",
                    ),
                ),
                (
                    "show_in_home_section",
                    models.BooleanField(
                        default=True,
                        help_text="A full banner card in the flow of the home page.",
                    ),
                ),
                (
                    "modal_frequency",
                    models.CharField(
                        choices=[
                            ("once", "Once per visitor"),
                            ("daily", "Once a day"),
                            ("every_visit", "Every visit"),
                        ],
                        default="daily",
                        help_text="How often one visitor sees the modal. 'Every visit' is deliberately available but annoys returning customers — prefer 'Once a day'.",
                        max_length=12,
                    ),
                ),
                (
                    "modal_delay_seconds",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Seconds before the modal opens. A short delay lets the page paint first; opening instantly reads as a popup ad.",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When it begins showing (Bangladesh time). Blank means immediately, so a promotion can be written today and published the moment it is switched on.",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When it stops showing. Blank means it runs until switched off by hand — which someone has to remember to do, so prefer setting a date.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="The manual switch, on top of the dates. Unchecking hides it everywhere at once without deleting the content.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Lower shows first when more than one promotion is live. The modal and the hero strip only ever show the first one.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_package",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. When set, the button goes to this sailing and the promotion disappears on its own once the sailing has departed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotions",
                        to="packages.package",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="ships.ship",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "sort_order"],
                        name="promotions__is_acti_02c033_idx",
                    )
                ],
            },
        ),
    ]
