"""Rename show_in_hero -> show_in_top_bar.

Written by hand as a RenameField. `makemigrations` autogenerated a
RemoveField + AddField pair, which is a different operation entirely: it would
drop the column and create a fresh one, silently resetting every promotion's
setting to the default. Harmless here (no rows existed yet) and destructive on
the sister site, which may well have promotions by the time this is applied
there.

The placement moved from a strip inside the hero to a bar pinned above the
navigation, so the old name had stopped describing what the field does.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promotion",
            old_name="show_in_hero",
            new_name="show_in_top_bar",
        ),
        migrations.AlterField(
            model_name="promotion",
            name="show_in_top_bar",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "A slim bar pinned above the navigation, on every page of "
                    "the site."
                ),
            ),
        ),
    ]
