# Generated by Django 5.1.15 on 2026-08-09 12:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0013_booking_booking_type"),
        ("ships", "0015_ship_group_min_pax_ship_refund_claim_window_days_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CancellationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("customer", "Customer (website)"),
                            ("staff", "Staff (phone / desk)"),
                        ],
                        default="customer",
                        max_length=10,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("plans_changed", "Plans changed"),
                            ("medical", "Illness / emergency"),
                            ("date_change", "Wants a different date"),
                            ("booked_by_mistake", "Booked by mistake"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason_note", models.TextField(blank=True)),
                ("booking_type", models.CharField(blank=True, max_length=12)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "cancellation_charge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="max(0, paid − charge). Never negative: a refund cannot bill.",
                        max_digits=12,
                    ),
                ),
                (
                    "forfeited_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="min(paid, charge) — what the company keeps.",
                        max_digits=12,
                    ),
                ),
                (
                    "shortfall_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="max(0, charge − paid): charge the deposit did not cover. Recorded for reporting only — waived by default, never invoiced.",
                        max_digits=12,
                    ),
                ),
                (
                    "policy_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The tier, percentages and dates this quote was computed from. Editing the schedule later must not move an existing request.",
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("bank_transfer", "Bank transfer"),
                            ("cash", "Cash"),
                            ("gateway", "Back to the payment gateway"),
                        ],
                        max_length=16,
                    ),
                ),
                ("refund_account_name", models.CharField(blank=True, max_length=120)),
                ("refund_account_number", models.CharField(blank=True, max_length=40)),
                ("bank_name", models.CharField(blank=True, max_length=120)),
                ("branch_name", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn by customer"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_requests",
                        to="bookings.booking",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancellation_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="CancellationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "days_before_start",
                    models.PositiveSmallIntegerField(
                        help_text="Applies when the cancellation lands this many whole days or more before departure (and fewer than the next tier up). Use 0 for the final-day catch-all."
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Shown to the customer, e.g. "3 weeks before departure".',
                        max_length=60,
                    ),
                ),
                (
                    "individual_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="% of the booking total charged on an individual booking.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "group_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="% charged on a group booking (see Booking.booking_type).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for the default schedule used by every ship. Set a ship to give that ship its own complete schedule (its rows then replace the default entirely).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_rules",
                        to="ships.ship",
                    ),
                ),
            ],
            options={
                "ordering": ["-days_before_start"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("customer_cancellation", "Customer cancellation"),
                            ("operator_cancellation", "Operator cancellation"),
                            ("overpayment", "Overpayment"),
                            ("duplicate_payment", "Duplicate payment"),
                            ("goodwill", "Goodwill / service issue"),
                        ],
                        max_length=24,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cancellation_charge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("policy_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending payout"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                            ("void", "Void / raised in error"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("bank_transfer", "Bank transfer"),
                            ("cash", "Cash"),
                            ("gateway", "Back to the payment gateway"),
                        ],
                        max_length=16,
                    ),
                ),
                ("account_name", models.CharField(blank=True, max_length=120)),
                ("account_number", models.CharField(blank=True, max_length=40)),
                ("bank_name", models.CharField(blank=True, max_length=120)),
                ("branch_name", models.CharField(blank=True, max_length=120)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        help_text="bKash/bank transaction id — required to reconcile the payout.",
                        max_length=64,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="bookings.booking",
                    ),
                ),
                (
                    "cancellation_request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund",
                        to="refunds.cancellationrequest",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null when raised automatically by the system.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefundStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=10)),
                ("new_status", models.CharField(max_length=10)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="refunds.refund",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cancellationrequest",
            index=models.Index(
                fields=["status", "-requested_at"], name="cxreq_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cancellationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("booking",),
                name="one_open_cancellation_request_per_booking",
            ),
        ),
        migrations.AddConstraint(
            model_name="cancellationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("refund_amount__gte", 0),
                    ("cancellation_charge__gte", 0),
                    ("forfeited_amount__gte", 0),
                    ("shortfall_amount__gte", 0),
                ),
                name="cancellation_request_amounts_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="cancellationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("refund_amount__lte", models.F("paid_amount"))),
                name="cancellation_refund_within_paid",
            ),
        ),
        migrations.AddConstraint(
            model_name="cancellationrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ship__isnull", False)),
                fields=("ship", "days_before_start"),
                name="uniq_ship_cancellation_tier",
            ),
        ),
        migrations.AddConstraint(
            model_name="cancellationrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ship__isnull", True)),
                fields=("days_before_start",),
                name="uniq_default_cancellation_tier",
            ),
        ),
        migrations.AddConstraint(
            model_name="cancellationrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("individual_percent__gte", 0),
                    ("individual_percent__lte", 100),
                    ("group_percent__gte", 0),
                    ("group_percent__lte", 100),
                ),
                name="cancellation_percent_within_0_100",
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["status", "-created_at"], name="refund_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["reason"], name="refund_reason_idx"),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="refund_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("booking",),
                name="one_open_refund_per_booking",
            ),
        ),
    ]
