# Generated by Django 5.1.15 on 2026-07-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partially_paid", "Partially paid"),
                    ("fully_paid", "Fully paid"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bookingstatuslog",
            name="new_status",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="bookingstatuslog",
            name="old_status",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("transaction_id", ""), _negated=True),
                fields=("transaction_id",),
                name="uniq_payment_transaction_id",
            ),
        ),
    ]
