# Generated by Django 5.1.15 on 2026-07-11 10:21

from django.db import migrations, models
from django.db.models import Sum


def repair_money_state(apps, schema_editor):
    """One-off repair of rows created while the QA Phase 5 bugs were live,
    so the new CHECK constraints can be applied:

    - C4 artifacts: non-positive Payment rows are corrupt by definition (a
      'negative payment' silently erased settled money) — remove them and
      recompute the affected bookings' paid/due from the surviving payments.
    - C3 artifacts: clamp negative dues (staff overpayment) to zero and flag
      the booking for a manual refund call.
    - M1 catch-up: cancelled bookings carry no collectable balance.
    - H3 catch-up: flag existing cancelled-with-deposit bookings so they
      appear in the new refunds-owed queue.
    """
    Booking = apps.get_model("bookings", "Booking")
    Payment = apps.get_model("bookings", "Payment")

    bad_payments = Payment.objects.filter(amount__lte=0)
    affected_ids = list(bad_payments.values_list("booking_id", flat=True))
    bad_payments.delete()
    for booking in Booking.objects.filter(pk__in=affected_ids):
        paid = booking.payments.filter(status="success").aggregate(
            s=Sum("amount")
        )["s"] or 0
        booking.paid_amount = paid
        booking.due_amount = booking.total_amount - paid
        booking.save(update_fields=["paid_amount", "due_amount"])

    Booking.objects.filter(status="cancelled").exclude(due_amount=0).update(
        due_amount=0
    )
    Booking.objects.filter(due_amount__lt=0).update(
        due_amount=0, refund_required=True
    )
    Booking.objects.filter(status="cancelled", paid_amount__gt=0).update(
        refund_required=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_status_and_more"),
        ("packages", "0004_package_balance_due_days_before_start_and_more"),
        ("ships", "0006_seed_mv_alaska_food_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="due_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="refund_note",
            field=models.TextField(
                blank=True, help_text="Why a refund is owed / how it was settled."
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="refund_required",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(repair_money_state, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("due_amount__gte", 0)),
                name="booking_due_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payment_amount_positive"
            ),
        ),
    ]
