# Generated by Django 5.1.15 on 2026-07-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_move_invoice_pdfs_to_token_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="last_reconcile_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
