# Generated by Django 5.1.15 on 2026-07-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_payment_last_reconcile_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="special_requests",
            field=models.TextField(blank=True),
        ),
    ]
