# Generated by Django 5.1.15 on 2026-07-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_booking_special_requests"),
        ("packages", "0005_alter_package_min_deposit_percent"),
        ("ships", "0007_ship_authority_phones"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="booking_status_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["-created_at"], name="booking_created_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["package", "status"], name="booking_package_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["created_at"],
                name="payment_pending_idx",
            ),
        ),
    ]
