# Generated by Django 5.1.15 on 2026-07-15 13:48

import apps.bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_booking_booking_status_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                storage=apps.bookings.models.select_invoice_storage,
                upload_to=apps.bookings.models.invoice_pdf_path,
            ),
        ),
    ]
