# Generated by Django 5.1.15 on 2026-08-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_bookingroom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingroom",
            name="foreign_guests",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Foreign nationals in this cabin, e.g. [{"guest_type": "adult", "passport_number": "A1234567"}]. A subset of the cabin\'s pax — each one adds the package\'s foreigner surcharge.',
            ),
        ),
    ]
