# Generated by Django 5.1.15 on 2026-08-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0012_bookingroom_foreign_guests"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_type",
            field=models.CharField(
                choices=[("individual", "Individual"), ("group", "Group")],
                default="individual",
                help_text="Group bookings use the group column of the cancellation-charge schedule. Set by staff — never inferred from headcount.",
                max_length=12,
            ),
        ),
    ]
