# Generated by Django 5.1.15 on 2026-09-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0013_booking_booking_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="gateway_risk_level",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
