"""Refund register — the accounting view of money going back out.

Two outputs from one query:

- **PDF**, for the file and for whoever signs things off.
- **CSV**, because the person who actually reconciles this against the
  SSLCommerz settlement report and the bKash statement works in a spreadsheet,
  and handing them a PDF is handing them retyping.

The register is deliberately reason-aware. "We refunded 240,000 BDT this month"
means very different things depending on whether it was customer cancellations
(normal churn), operator cancellations (a sailing we could not run) or goodwill
(service failures) — so the totals break down by reason as well as summing.

Reuses the invoice/guide-report PDF stack (fpdf2 + the Noto fonts, so Bengali
customer names render rather than turning into boxes).
"""

import csv
import io
from decimal import Decimal

from django.utils import timezone
from fpdf import FPDF

from apps.bookings.branding import draw_header_logo, draw_watermark
from apps.bookings.invoices import FONTS_DIR

from .models import Refund

NAVY = (16, 46, 80)
ZEBRA = (247, 249, 251)
GREY = (105, 115, 125)
RULE = (210, 216, 222)
RED = (176, 58, 58)

ZERO = Decimal("0.00")

COLUMNS = [
    ("Date", 20),
    ("Booking", 30),
    ("Customer", 42),
    ("Phone", 26),
    ("Reason", 34),
    ("Paid", 22),
    ("Charge", 22),
    ("Refund", 24),
    ("Status", 20),
    ("Method", 22),
    ("Reference", 34),
]


def register_queryset(*, date_from=None, date_to=None, package=None, status=None):
    """The rows a register covers.

    VOID refunds are excluded by default: they are raised-in-error rows kept for
    the audit trail, and including them in a financial summary would overstate
    both what was owed and what went out.
    """
    qs = Refund.objects.select_related(
        "booking", "booking__package", "booking__package__ship", "processed_by"
    ).exclude(status=Refund.Status.VOID)
    if status:
        qs = qs.filter(status=status)
    if date_from:
        qs = qs.filter(created_at__date__gte=date_from)
    if date_to:
        qs = qs.filter(created_at__date__lte=date_to)
    if package:
        qs = qs.filter(booking__package=package)
    return qs.order_by("created_at")


def register_totals(refunds):
    """Summed once, in Python, over the same rows the document prints — so the
    totals line can never disagree with the table above it (which a second
    aggregate query, run against a shifting table, eventually would)."""
    totals = {
        "count": 0,
        "refunded": ZERO,
        "pending": ZERO,
        "charges_kept": ZERO,
        "by_reason": {},
    }
    for refund in refunds:
        totals["count"] += 1
        totals["charges_kept"] += refund.cancellation_charge
        if refund.status == Refund.Status.PAID:
            totals["refunded"] += refund.amount
        elif refund.status == Refund.Status.PENDING:
            totals["pending"] += refund.amount
        bucket = totals["by_reason"].setdefault(
            refund.get_reason_display(), {"count": 0, "amount": ZERO}
        )
        bucket["count"] += 1
        bucket["amount"] += refund.amount
    return totals


def generate_register_csv(refunds):
    """Reconciliation-shaped CSV: one row per payout, amounts unformatted so the
    spreadsheet treats them as numbers."""
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(
        [
            "Raised",
            "Paid",
            "Booking",
            "Customer",
            "Phone",
            "Departure",
            "Reason",
            "Paid by customer",
            "Cancellation charge",
            "Refund amount",
            "Status",
            "Method",
            "Account",
            "Reference",
            "Processed by",
            "Note",
        ]
    )
    for refund in refunds:
        booking = refund.booking
        writer.writerow(
            [
                timezone.localtime(refund.created_at).strftime("%Y-%m-%d"),
                timezone.localtime(refund.paid_at).strftime("%Y-%m-%d")
                if refund.paid_at
                else "",
                booking.booking_code,
                booking.customer_name,
                booking.phone,
                booking.package.start_date.isoformat(),
                refund.get_reason_display(),
                booking.paid_amount,
                refund.cancellation_charge,
                refund.amount,
                refund.get_status_display(),
                refund.get_method_display(),
                # The full account number belongs in the reconciliation file:
                # this CSV is generated by an admin, for finance, and matching a
                # bKash statement line needs the number that was paid.
                refund.account_number,
                refund.reference_no,
                refund.processed_by.get_username() if refund.processed_by_id else "",
                refund.note.replace("\n", " / "),
            ]
        )
    return buffer.getvalue()


def _fmt(amount):
    return f"{amount:,.2f}"


def generate_register_pdf(refunds, *, ship, date_from=None, date_to=None):
    refunds = list(refunds)
    totals = register_totals(refunds)

    pdf = FPDF(orientation="L")  # landscape: eleven columns need the width
    pdf.set_auto_page_break(auto=True, margin=14)
    pdf.add_page()
    pdf.add_font("NotoSans", "", FONTS_DIR / "NotoSans-Regular.ttf")
    pdf.add_font("NotoSans", "B", FONTS_DIR / "NotoSans-Bold.ttf")
    pdf.add_font("NotoSansBengali", "", FONTS_DIR / "NotoSansBengali-Regular.ttf")
    pdf.add_font("NotoSansBengali", "B", FONTS_DIR / "NotoSansBengali-Bold.ttf")
    pdf.set_fallback_fonts(["NotoSansBengali"])
    pdf.set_text_shaping(True)
    epw = pdf.epw

    pdf.set_fill_color(*NAVY)
    pdf.rect(0, 0, pdf.w, 2.5, "F")
    draw_header_logo(pdf, pdf.l_margin, 6, 15)

    pdf.set_xy(pdf.l_margin + 20, 8)
    pdf.set_text_color(*NAVY)
    pdf.set_font("NotoSans", "B", 14)
    pdf.cell(epw / 2, 7, f"{ship.name} — Refund Register", new_x="LMARGIN", new_y="NEXT")

    period = "All time"
    if date_from or date_to:
        period = f"{date_from or '…'} to {date_to or '…'}"
    pdf.set_xy(pdf.l_margin + 20, 15)
    pdf.set_text_color(*GREY)
    pdf.set_font("NotoSans", "", 8.5)
    pdf.cell(
        epw / 2,
        5,
        f"Period: {period}   ·   Generated "
        f"{timezone.localtime():%d %b %Y %H:%M}",
        new_x="LMARGIN",
        new_y="NEXT",
    )

    pdf.set_y(26)

    # ── Table header ──
    pdf.set_font("NotoSans", "B", 8)
    pdf.set_fill_color(*NAVY)
    pdf.set_text_color(255, 255, 255)
    for label, width in COLUMNS:
        pdf.cell(width, 7, label, border=0, align="L", fill=True)
    pdf.ln()

    pdf.set_font("NotoSans", "", 8)
    pdf.set_text_color(30, 36, 44)
    for index, refund in enumerate(refunds):
        booking = refund.booking
        if pdf.will_page_break(6):
            pdf.add_page()
        fill = index % 2 == 1
        if fill:
            pdf.set_fill_color(*ZEBRA)
        values = [
            timezone.localtime(refund.created_at).strftime("%d %b"),
            booking.booking_code,
            booking.customer_name[:24],
            booking.phone,
            refund.get_reason_display()[:22],
            _fmt(booking.paid_amount),
            _fmt(refund.cancellation_charge),
            _fmt(refund.amount),
            refund.get_status_display(),
            refund.get_method_display() or "—",
            refund.reference_no or "—",
        ]
        # A pending row is a debt the company is still carrying — the one thing
        # a reader of this page must not skim past.
        if refund.status == Refund.Status.PENDING:
            pdf.set_text_color(*RED)
        for (label, width), value in zip(COLUMNS, values):
            align = "R" if label in ("Paid", "Charge", "Refund") else "L"
            pdf.cell(width, 6, str(value), border=0, align=align, fill=fill)
        pdf.set_text_color(30, 36, 44)
        pdf.ln()

    if not refunds:
        pdf.set_text_color(*GREY)
        pdf.cell(epw, 10, "No refunds in this period.", align="C")
        pdf.ln()

    # ── Totals ──
    pdf.ln(3)
    pdf.set_draw_color(*RULE)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("NotoSans", "B", 9.5)
    pdf.set_text_color(*NAVY)
    pdf.cell(60, 6, f"Refunds: {totals['count']}")
    pdf.cell(70, 6, f"Paid out: {_fmt(totals['refunded'])} BDT")
    pdf.set_text_color(*RED)
    pdf.cell(
        80, 6, f"Still owed (liability): {_fmt(totals['pending'])} BDT"
    )
    pdf.set_text_color(*NAVY)
    pdf.cell(70, 6, f"Charges retained: {_fmt(totals['charges_kept'])} BDT")
    pdf.ln(9)

    if totals["by_reason"]:
        pdf.set_font("NotoSans", "B", 8.5)
        pdf.set_text_color(*GREY)
        pdf.cell(epw, 5, "BY REASON", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("NotoSans", "", 8.5)
        pdf.set_text_color(30, 36, 44)
        for reason, bucket in sorted(totals["by_reason"].items()):
            pdf.cell(70, 5, reason)
            pdf.cell(30, 5, str(bucket["count"]), align="R")
            pdf.cell(40, 5, f"{_fmt(bucket['amount'])} BDT", align="R")
            pdf.ln()

    draw_watermark(pdf, ship.name)
    return bytes(pdf.output())
